# Generated by Django 5.0.6 on 2024-06-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='generated_key',
            field=models.CharField(default='wuM4sCegwl', max_length=255, unique=True),
        ),
    ]
