# Generated by Django 5.0.6 on 2024-06-04 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tournament_generated_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='next_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.match'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='generated_key',
            field=models.CharField(default='pMoVYf7Vxu', max_length=255, unique=True),
        ),
    ]
